# MACHINE LEARNING:(DATA GATHERING.)

### FETCHING A DATA FROM AN API:

In [1]:
import pandas as pd 
import requests

### API KEY PASTE

In [3]:
response =  requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=3c67f46b38ab165a060b882feb907f0a&langage=en-US&page=1')

### COLLECTING A WHOLE DATA FROM  AN API:

### GET A DATA FROM PAGE 1:

In [6]:
df = pd.DataFrame(response.json()['results'])

### DF SHOWS

In [7]:
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,166.609,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.700,26449
1,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",167.615,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.692,20085
2,False,/b6w7gKLQLS2zw4JK0XmKgQ4gnzr.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,124.249,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.576,12120
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,124.504,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.567,15521
4,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,110.113,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.500,8361
5,False,/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",142.913,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.537,16115
6,False,/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",49.278,/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.536,4404
7,False,/dqK9Hag1054tghRQSqLSfrkvQnA.jpg,"[18, 28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,163.284,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.516,32208
8,False,/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",142.919,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.509,17754
9,False,/vxJ08SvwomfKbpboCWynC3uqUg4.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,91.906,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,The Green Mile,False,8.506,16984
10,False,/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg,"[16, 10749, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,144.235,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.490,11098
11,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",98.883,/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg,1994-09-10,Pulp Fiction,False,8.488,27363
12,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,121.615,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-01,The Lord of the Rings: The Return of the King,False,8.500,23627
13,False,/mzfx54nfDPTUXZOG48u4LaEheDy.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,87.541,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg,1994-06-23,Forrest Gump,False,8.475,26875
14,False,/d6UxFCGQxpszcf8mwgGjQ3ynqGl.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",82.867,/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg,1990-09-12,GoodFellas,False,8.464,12549
15,False,/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,115.361,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-22,"The Good, the Bad and the Ugly",False,8.500,8370
16,False,/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg,"[10751, 18]",667257,es,Cosas imposibles,"After the death of her abusive husband, Matild...",15.920,/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg,2021-06-17,Impossible Things,False,8.459,379
17,False,/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.075,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,Grave of the Fireflies,False,8.459,5318
18,False,/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,58.242,/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg,1954-04-26,Seven Samurai,False,8.458,3554
19,False,/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg,"[35, 18]",637,it,La vita è bella,A touching story of an Italian book seller of ...,64.669,/74hLDKjD5aGYOotO6esUVaeISa2.jpg,1997-12-20,Life Is Beautiful,False,8.451,12804

In [20]:
df.shape

(20, 6)

### COLLECTING A 6 COLUMNS FROM API:

In [8]:
df = pd.DataFrame(response.json()['results'])[['id','title','release_date','overview','popularity','vote_average']] 
df

,id,title,release_date,overview,popularity,vote_average
0,278,The Shawshank Redemption,1994-09-23,Imprisoned in the 1940s for the double murder ...,166.609,8.700
1,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",167.615,8.692
2,240,The Godfather Part II,1974-12-20,In the continuing saga of the Corleone crime f...,124.249,8.576
3,424,Schindler's List,1993-12-15,The true story of how businessman Oskar Schind...,124.504,8.567
4,389,12 Angry Men,1957-04-10,The defense and the prosecution have rested an...,110.113,8.500
5,129,Spirited Away,2001-07-20,"A young girl, Chihiro, becomes trapped in a st...",142.913,8.537
6,19404,Dilwale Dulhania Le Jayenge,1995-10-20,"Raj is a rich, carefree, happy-go-lucky second...",49.278,8.536
7,155,The Dark Knight,2008-07-16,Batman raises the stakes in his war on crime. ...,163.284,8.516
8,496243,Parasite,2019-05-30,"All unemployed, Ki-taek's family takes peculia...",142.919,8.509
9,497,The Green Mile,1999-12-10,A supernatural tale set on death row in a Sout...,91.906,8.506
10,372058,Your Name.,2016-08-26,High schoolers Mitsuha and Taki are complete s...,144.235,8.490
11,680,Pulp Fiction,1994-09-10,"A burger-loving hit man, his philosophical par...",98.883,8.488
12,122,The Lord of the Rings: The Return of the King,2003-12-01,As armies mass for a final battle that will de...,121.615,8.500
13,13,Forrest Gump,1994-06-23,A man with a low IQ has accomplished great thi...,87.541,8.475
14,769,GoodFellas,1990-09-12,"The true story of Henry Hill, a half-Irish, ha...",82.867,8.464
15,429,"The Good, the Bad and the Ugly",1966-12-22,While the Civil War rages on between the Union...,115.361,8.500
16,667257,Impossible Things,2021-06-17,"After the death of her abusive husband, Matild...",15.920,8.459
17,12477,Grave of the Fireflies,1988-04-16,"In the final months of World War II, 14-year-o...",0.075,8.459
18,346,Seven Samurai,1954-04-26,A samurai answers a village's request for prot...,58.242,8.458
19,637,Life Is Beautiful,1997-12-20,A touching story of an Italian book seller of ...,64.669,8.451

In [9]:
df.head()

,id,title,release_date,overview,popularity,vote_average
0,278,The Shawshank Redemption,1994-09-23,Imprisoned in the 1940s for the double murder ...,166.609,8.700
1,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",167.615,8.692
2,240,The Godfather Part II,1974-12-20,In the continuing saga of the Corleone crime f...,124.249,8.576
3,424,Schindler's List,1993-12-15,The true story of how businessman Oskar Schind...,124.504,8.567
4,389,12 Angry Men,1957-04-10,The defense and the prosecution have rested an...,110.113,8.500

In [10]:
df.tail()

,id,title,release_date,overview,popularity,vote_average
15,429,"The Good, the Bad and the Ugly",1966-12-22,While the Civil War rages on between the Union...,115.361,8.500
16,667257,Impossible Things,2021-06-17,"After the death of her abusive husband, Matild...",15.920,8.459
17,12477,Grave of the Fireflies,1988-04-16,"In the final months of World War II, 14-year-o...",0.075,8.459
18,346,Seven Samurai,1954-04-26,A samurai answers a village's request for prot...,58.242,8.458
19,637,Life Is Beautiful,1997-12-20,A touching story of an Italian book seller of ...,64.669,8.451

### GET A DATA FROM PAGE 5:

In [11]:
response =  requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=3c67f46b38ab165a060b882feb907f0a&langage=en-US&page=5')
df1 = pd.DataFrame(response.json()['results'])
df1

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/6rmb35g7XoMCMQtnbH0rUecFZlV.jpg,"[18, 10402]",10376,it,La leggenda del pianista sull'oceano,The story of a virtuoso piano player who lives...,36.253,/4EKnIjT1IGGFyplaW11lTvXrzI0.jpg,1998-10-28,The Legend of 1900,False,8.263,2205
1,False,/88J6waYVTta8Qz3iX3qUeWNA5d5.jpg,"[18, 10749]",447362,en,Life in a Year,A 17 year old finds out that his girlfriend is...,63.517,/bP7u19opmHXYeTCUwGjlLldmUMc.jpg,2020-11-27,Life in a Year,False,8.263,1800
2,False,/xGzcusHWxLPvRYSBMeOJOVkdJbj.jpg,"[18, 10752]",25237,ru,Иди и смотри,The invasion of a village in Byelorussia by Ge...,66.961,/qNbMsKVzigERgJUbwf8pKyZogpb.jpg,1985-10-17,Come and See,False,8.261,1412
3,False,/1EAxNqdkVnp48a7NUuNBHGflowM.jpg,"[16, 28, 878, 18]",283566,ja,シン・エヴァンゲリオン劇場版:||,"In the aftermath of the Fourth Impact, strande...",82.447,/md5wZRRj8biHrGtyitgBZo7674t.jpg,2021-03-08,Evangelion: 3.0+1.0 Thrice Upon a Time,False,8.258,766
4,False,/wXsQvli6tWqja51pYxXNG1LFIGV.jpg,"[10751, 16, 18]",8587,en,The Lion King,A young lion prince is cast out of his pride b...,175.087,/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg,1994-06-24,The Lion King,False,8.257,17877
5,False,/nbAbAk80aWCpOS5kOPYJ1L9kE1R.jpg,"[10402, 18, 10749]",630566,en,Clouds,Young musician Zach Sobiech discovers his canc...,17.349,/d0OdD1I8qAfETvE9Rp9Voq7R8LR.jpg,2020-10-09,Clouds,False,8.255,989
6,False,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"[12, 878, 28]",299534,en,Avengers: Endgame,After the devastating events of Avengers: Infi...,105.182,/or06FN3Dka5tukK1e9sl16pB3iy.jpg,2019-04-24,Avengers: Endgame,False,8.254,25085
7,False,/sdwjQEM869JFwMytTmvr6ggvaUl.jpg,"[18, 53, 9648, 28]",670,ko,올드보이,"With no clue how he came to be imprisoned, dru...",73.911,/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg,2003-11-21,Oldboy,False,8.254,8397
8,False,/aLqtWLA6NQHBwQHvHDq5z4EKUm0.jpg,"[16, 14, 10749, 18]",533514,ja,劇場版 ヴァイオレット・エヴァーガーデン,As the world moves on from the war and technol...,70.865,/A9R6bukzzRmOzxvDQsXdQpeNm8l.jpg,2020-09-18,Violet Evergarden: The Movie,False,8.200,397
9,False,/mlxKite1x1PgmIhJgAxNS9eHmH8.jpg,"[16, 10751, 12, 35, 14]",508965,en,Klaus,When Jesper distinguishes himself as the Posta...,27.010,/q125RHUDgR4gjwh1QkfYuJLYkL.jpg,2019-11-08,Klaus,False,8.246,3905
10,False,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"[12, 28, 878]",299536,en,Avengers: Infinity War,As the Avengers and their allies have continue...,169.719,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,2018-04-25,Avengers: Infinity War,False,8.246,29124
11,False,/2Xe9lISpwXKhvKiHttbFfVRERQX.jpg,"[18, 36]",490132,en,Green Book,"Tony Lip, a bouncer in 1962, is hired to drive...",49.223,/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg,2018-11-16,Green Book,False,8.243,11309
12,False,/2Kkqmy3EpXqBDqv1vvsNXX3pwww.jpg,"[18, 35]",42269,it,C'eravamo tanto amati,Three partisans bound by a strong friendship r...,11.536,/zGGWYpiKNwjpKxelPxOMqJnUgDs.jpg,1974-12-21,We All Loved Each Other So Much,False,8.237,520
13,False,/jr8tSoJGj33XLgFBy6lmZhpGQNu.jpg,"[16, 12, 14, 35, 10751]",315162,en,Puss in Boots: The Last Wish,Puss in Boots discovers that his passion for a...,230.514,/kuf6dutpsT0vSVehic3EZIqkOBt.jpg,2022-12-07,Puss in Boots: The Last Wish,False,8.236,7403
14,False,/oA7EHjQPgtPKSrvtNtzA82opnrQ.jpg,[18],265177,fr,Mommy,A peculiar neighbor offers hope to a recent wi...,15.840,/nT4VJ6MfSwUoCorYmkcLVaIenya.jpg,2014-09-19,Mommy,False,8.235,2664
15,False,/sQkRiQo3nLrQYMXZodDjNUJKHZV.jpg,"[16, 28, 878]",618344,en,Justice League Dark: Apokolips War,Earth is decimated after intergalactic tyrant ...,49.177,/c01Y4suApJ1Wic2xLmaq1QYcfoZ.jpg,2020-05-05,Justice League Dark: Apokolips War,False,8.200,1428
16,False,/eNWjMbuhGxJdzaIY9ZZ2KvWx2sQ.jpg,"[16, 10751, 18, 14]",110420,ja,おおかみこどもの雨と雪,After her werewolf lover unexpectedly dies in ...,70.388,/3Nllh6JgcrFdtOn6iFOWHudNInd.jpg,2012-07-21,Wolf Children,False,8.233,2222
17,False,/tyxqfALuq02khuKNCwmeMxrqt8T.jpg,"[16, 10749, 18, 14]",572154,ja,青春ブタ野郎はゆめみる少女の夢を見ない,"In Fujisawa, Sakuta Azusagawa is in his second...",50.701,/gsRpizQa3fw1um8v7EvFVXvxD6u.jpg,2019-06-15,Rascal Does Not Dream of a Dreaming Girl,False,8.231,508
18,False,/YLyORLsYIjC0d1TFBSpJKk7piP.jpg,"[16, 18, 10749]",504253,ja,君の膵臓をたべたい,After his classmate and crush is diagnosed wit...,66.718,/qpV8kvRfAntV7D4aOOsLIz7OdPc.jpg,2018-09-01,I Want to Eat Your Pancreas,False,8.229,1492
19,False,/qjGrUmKW78MCFG8PTLDBp67S27p.jpg,"[28, 16, 12, 14, 53]",635302,ja,劇場版「鬼滅の刃」無限列車編,"Tanjiro Kamado, joined with Inosuke Hashibira,...",204.508,/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg,2020-10-16,Demon Slayer -Kimetsu no Yaiba- The Movie: Mug...,False,8.226,3774

In [18]:
df1 = pd.DataFrame(response.json()['results'])[['id','title','release_date','overview','popularity','vote_average']] 
df1

,id,title,release_date,overview,popularity,vote_average
0,10376,The Legend of 1900,1998-10-28,The story of a virtuoso piano player who lives...,36.253,8.263
1,447362,Life in a Year,2020-11-27,A 17 year old finds out that his girlfriend is...,63.517,8.263
2,25237,Come and See,1985-10-17,The invasion of a village in Byelorussia by Ge...,66.961,8.261
3,283566,Evangelion: 3.0+1.0 Thrice Upon a Time,2021-03-08,"In the aftermath of the Fourth Impact, strande...",82.447,8.258
4,8587,The Lion King,1994-06-24,A young lion prince is cast out of his pride b...,175.087,8.257
5,630566,Clouds,2020-10-09,Young musician Zach Sobiech discovers his canc...,17.349,8.255
6,299534,Avengers: Endgame,2019-04-24,After the devastating events of Avengers: Infi...,105.182,8.254
7,670,Oldboy,2003-11-21,"With no clue how he came to be imprisoned, dru...",73.911,8.254
8,533514,Violet Evergarden: The Movie,2020-09-18,As the world moves on from the war and technol...,70.865,8.200
9,508965,Klaus,2019-11-08,When Jesper distinguishes himself as the Posta...,27.010,8.246
10,299536,Avengers: Infinity War,2018-04-25,As the Avengers and their allies have continue...,169.719,8.246
11,490132,Green Book,2018-11-16,"Tony Lip, a bouncer in 1962, is hired to drive...",49.223,8.243
12,42269,We All Loved Each Other So Much,1974-12-21,Three partisans bound by a strong friendship r...,11.536,8.237
13,315162,Puss in Boots: The Last Wish,2022-12-07,Puss in Boots discovers that his passion for a...,230.514,8.236
14,265177,Mommy,2014-09-19,A peculiar neighbor offers hope to a recent wi...,15.840,8.235
15,618344,Justice League Dark: Apokolips War,2020-05-05,Earth is decimated after intergalactic tyrant ...,49.177,8.200
16,110420,Wolf Children,2012-07-21,After her werewolf lover unexpectedly dies in ...,70.388,8.233
17,572154,Rascal Does Not Dream of a Dreaming Girl,2019-06-15,"In Fujisawa, Sakuta Azusagawa is in his second...",50.701,8.231
18,504253,I Want to Eat Your Pancreas,2018-09-01,After his classmate and crush is diagnosed wit...,66.718,8.229
19,635302,Demon Slayer -Kimetsu no Yaiba- The Movie: Mug...,2020-10-16,"Tanjiro Kamado, joined with Inosuke Hashibira,...",204.508,8.226

In [13]:
df1.head()

,id,title,release_date,overview,popularity,vote_average
0,10376,The Legend of 1900,1998-10-28,The story of a virtuoso piano player who lives...,36.253,8.263
1,447362,Life in a Year,2020-11-27,A 17 year old finds out that his girlfriend is...,63.517,8.263
2,25237,Come and See,1985-10-17,The invasion of a village in Byelorussia by Ge...,66.961,8.261
3,283566,Evangelion: 3.0+1.0 Thrice Upon a Time,2021-03-08,"In the aftermath of the Fourth Impact, strande...",82.447,8.258
4,8587,The Lion King,1994-06-24,A young lion prince is cast out of his pride b...,175.087,8.257

In [14]:
df1.tail()

,id,title,release_date,overview,popularity,vote_average
15,618344,Justice League Dark: Apokolips War,2020-05-05,Earth is decimated after intergalactic tyrant ...,49.177,8.200
16,110420,Wolf Children,2012-07-21,After her werewolf lover unexpectedly dies in ...,70.388,8.233
17,572154,Rascal Does Not Dream of a Dreaming Girl,2019-06-15,"In Fujisawa, Sakuta Azusagawa is in his second...",50.701,8.231
18,504253,I Want to Eat Your Pancreas,2018-09-01,After his classmate and crush is diagnosed wit...,66.718,8.229
19,635302,Demon Slayer -Kimetsu no Yaiba- The Movie: Mug...,2020-10-16,"Tanjiro Kamado, joined with Inosuke Hashibira,...",204.508,8.226

In [19]:
df1.shape

(20, 6)

### CONVERTING THE API FILE INTO CSV FILE

In [21]:
df1.to_csv('movies.csv')

In [22]:
df1

,id,title,release_date,overview,popularity,vote_average
0,10376,The Legend of 1900,1998-10-28,The story of a virtuoso piano player who lives...,36.253,8.263
1,447362,Life in a Year,2020-11-27,A 17 year old finds out that his girlfriend is...,63.517,8.263
2,25237,Come and See,1985-10-17,The invasion of a village in Byelorussia by Ge...,66.961,8.261
3,283566,Evangelion: 3.0+1.0 Thrice Upon a Time,2021-03-08,"In the aftermath of the Fourth Impact, strande...",82.447,8.258
4,8587,The Lion King,1994-06-24,A young lion prince is cast out of his pride b...,175.087,8.257
5,630566,Clouds,2020-10-09,Young musician Zach Sobiech discovers his canc...,17.349,8.255
6,299534,Avengers: Endgame,2019-04-24,After the devastating events of Avengers: Infi...,105.182,8.254
7,670,Oldboy,2003-11-21,"With no clue how he came to be imprisoned, dru...",73.911,8.254
8,533514,Violet Evergarden: The Movie,2020-09-18,As the world moves on from the war and technol...,70.865,8.200
9,508965,Klaus,2019-11-08,When Jesper distinguishes himself as the Posta...,27.010,8.246
10,299536,Avengers: Infinity War,2018-04-25,As the Avengers and their allies have continue...,169.719,8.246
11,490132,Green Book,2018-11-16,"Tony Lip, a bouncer in 1962, is hired to drive...",49.223,8.243
12,42269,We All Loved Each Other So Much,1974-12-21,Three partisans bound by a strong friendship r...,11.536,8.237
13,315162,Puss in Boots: The Last Wish,2022-12-07,Puss in Boots discovers that his passion for a...,230.514,8.236
14,265177,Mommy,2014-09-19,A peculiar neighbor offers hope to a recent wi...,15.840,8.235
15,618344,Justice League Dark: Apokolips War,2020-05-05,Earth is decimated after intergalactic tyrant ...,49.177,8.200
16,110420,Wolf Children,2012-07-21,After her werewolf lover unexpectedly dies in ...,70.388,8.233
17,572154,Rascal Does Not Dream of a Dreaming Girl,2019-06-15,"In Fujisawa, Sakuta Azusagawa is in his second...",50.701,8.231
18,504253,I Want to Eat Your Pancreas,2018-09-01,After his classmate and crush is diagnosed wit...,66.718,8.229
19,635302,Demon Slayer -Kimetsu no Yaiba- The Movie: Mug...,2020-10-16,"Tanjiro Kamado, joined with Inosuke Hashibira,...",204.508,8.226

In [23]:
df.to_csv('movies_page1.csv')
df

,id,title,release_date,overview,popularity,vote_average
0,278,The Shawshank Redemption,1994-09-23,Imprisoned in the 1940s for the double murder ...,166.609,8.700
1,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",167.615,8.692
2,240,The Godfather Part II,1974-12-20,In the continuing saga of the Corleone crime f...,124.249,8.576
3,424,Schindler's List,1993-12-15,The true story of how businessman Oskar Schind...,124.504,8.567
4,389,12 Angry Men,1957-04-10,The defense and the prosecution have rested an...,110.113,8.500
5,129,Spirited Away,2001-07-20,"A young girl, Chihiro, becomes trapped in a st...",142.913,8.537
6,19404,Dilwale Dulhania Le Jayenge,1995-10-20,"Raj is a rich, carefree, happy-go-lucky second...",49.278,8.536
7,155,The Dark Knight,2008-07-16,Batman raises the stakes in his war on crime. ...,163.284,8.516
8,496243,Parasite,2019-05-30,"All unemployed, Ki-taek's family takes peculia...",142.919,8.509
9,497,The Green Mile,1999-12-10,A supernatural tale set on death row in a Sout...,91.906,8.506
10,372058,Your Name.,2016-08-26,High schoolers Mitsuha and Taki are complete s...,144.235,8.490
11,680,Pulp Fiction,1994-09-10,"A burger-loving hit man, his philosophical par...",98.883,8.488
12,122,The Lord of the Rings: The Return of the King,2003-12-01,As armies mass for a final battle that will de...,121.615,8.500
13,13,Forrest Gump,1994-06-23,A man with a low IQ has accomplished great thi...,87.541,8.475
14,769,GoodFellas,1990-09-12,"The true story of Henry Hill, a half-Irish, ha...",82.867,8.464
15,429,"The Good, the Bad and the Ugly",1966-12-22,While the Civil War rages on between the Union...,115.361,8.500
16,667257,Impossible Things,2021-06-17,"After the death of her abusive husband, Matild...",15.920,8.459
17,12477,Grave of the Fireflies,1988-04-16,"In the final months of World War II, 14-year-o...",0.075,8.459
18,346,Seven Samurai,1954-04-26,A samurai answers a village's request for prot...,58.242,8.458
19,637,Life Is Beautiful,1997-12-20,A touching story of an Italian book seller of ...,64.669,8.451